import os
import sqlite3
from pathlib import Path

import psycopg2


ROOT = Path(__file__).resolve().parent
DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()


def create_schema(connection):
    with connection.cursor() as cursor:
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS portal_stats (
                region TEXT PRIMARY KEY,
                visits INTEGER NOT NULL DEFAULT 0,
                visitors INTEGER NOT NULL DEFAULT 0
            )
        ''')
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS trusted_sources (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                country TEXT NOT NULL,
                topic TEXT NOT NULL,
                source_name TEXT NOT NULL,
                feed_url TEXT,
                site_url TEXT,
                source_type TEXT NOT NULL DEFAULT 'rss',
                is_active INTEGER NOT NULL DEFAULT 1,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        cursor.execute('''
            DELETE FROM trusted_sources
            WHERE id NOT IN (
                SELECT MIN(id)
                FROM trusted_sources
                GROUP BY country, topic, source_name, COALESCE(feed_url, ''), COALESCE(site_url, '')
            )
        ''')
        cursor.execute('''
            CREATE UNIQUE INDEX IF NOT EXISTS idx_trusted_sources_unique
            ON trusted_sources (country, topic, source_name, feed_url, site_url)
        ''')


def migrate_table(cursor, sqlite_connection, table_name, columns):
    rows = sqlite_connection.execute(
        f"SELECT {', '.join(columns)} FROM {table_name}"
    ).fetchall()
    placeholders = ', '.join(['%s'] * len(columns))
    column_sql = ', '.join(columns)
    cursor.executemany(
        f'INSERT INTO {table_name} ({column_sql}) VALUES ({placeholders}) ON CONFLICT DO NOTHING',
        rows,
    )
    return len(rows)


def main():
    if not DATABASE_URL:
        raise SystemExit('Set DATABASE_URL to the PostgreSQL connection string first.')

    analytics_path = ROOT / 'unganishwa_analytics.sqlite3'
    sources_path = ROOT / 'trusted_sources.sqlite3'
    with sqlite3.connect(analytics_path) as analytics_sqlite, sqlite3.connect(sources_path) as sources_sqlite:
        with psycopg2.connect(DATABASE_URL) as postgres:
            create_schema(postgres)
            with postgres.cursor() as cursor:
                stats_count = migrate_table(cursor, analytics_sqlite, 'portal_stats', ('region', 'visits', 'visitors'))
                source_count = migrate_table(
                    cursor,
                    sources_sqlite,
                    'trusted_sources',
                    ('id', 'country', 'topic', 'source_name', 'feed_url', 'site_url', 'source_type', 'is_active', 'created_at'),
                )
                cursor.execute('''
                    SELECT setval(
                        pg_get_serial_sequence('trusted_sources', 'id'),
                        COALESCE(MAX(id), 1),
                        true
                    )
                    FROM trusted_sources
                ''')
            postgres.commit()

    print(f'Migrated {stats_count} analytics rows and {source_count} trusted-source rows.')


if __name__ == '__main__':
    main()